In [43]:
import numpy as np

Xtrain = np.genfromtxt("train.csv", delimiter = ",", usecols = range(0,5))
Ytrain = np.genfromtxt("train.csv", delimiter = ",", usecols = range(5,6))

Xtest = np.genfromtxt("test.csv", delimiter = ",")
Xtrain = np.delete(Xtrain, 0, 0)
print(Xtrain)
#Xtrain = addfeatures(Xtrain)
Ytrain = np.delete(Ytrain, 0 ,0)
Xtest = np.delete(Xtest, 0, 0)

[[ 0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [-0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [-1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [-1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]


In [44]:
from sklearn.linear_model import LinearRegression

alg1 = LinearRegression()
alg1.fit(Xtrain, Ytrain)
Y_pred = alg1.predict(Xtest)

np.savetxt("predictions_Assignment2.csv", Y_pred, fmt = "%.8f")